"""add offer id to deals

Revision ID: 6469a14fb1d7
Revises: 7c3e71e14991
Create Date: 2026-05-25 15:01:33.949261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6469a14fb1d7'
down_revision: Union[str, Sequence[str], None] = '7c3e71e14991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('offer_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_deals_offer_id', 'deals', ['offer_id'])
    op.create_foreign_key(None, 'deals', 'offers', ['offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint('uq_deals_offer_id', 'deals', type_='unique')
    op.drop_column('deals', 'offer_id')
    # ### end Alembic commands ###
