"""create items and deals

Revision ID: 7c3e71e14991
Revises: db1b96741f55
Create Date: 2026-05-25 13:45:08.589157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3e71e14991'
down_revision: Union[str, Sequence[str], None] = 'db1b96741f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('internal_value', sa.Integer(), nullable=True),
    sa.Column('valuation_source', sa.Text(), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('public_story', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('given_item_id', sa.UUID(), nullable=False),
    sa.Column('received_item_id', sa.UUID(), nullable=False),
    sa.Column('participant_user_id', sa.UUID(), nullable=True),
    sa.Column('participant_public_name', sa.String(length=255), nullable=True),
    sa.Column('participant_visible', sa.Boolean(), nullable=False),
    sa.Column('public_story', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=1000), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('deal_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['given_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['participant_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['received_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deals')
    op.drop_table('items')
    # ### end Alembic commands ###
